repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
    # exclude: ^tests/fixtures/
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.1.0
  hooks:
  - id: reorder-python-imports
    args: [--application-directories, '.:src', --py36-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.1
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--line-length=88]
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ['--max-line-length=88','--ignore=E203,E266,E402,E501,E741,W503']
