max_msg_iter: 10 # max num BP iterations each EM cycle
msg_conv_tol: 1.0e-4 # conv tol for differences between messages after BP update
max_iter: 30 # max num EM iterations
conv_tol: 1.0e-4 # total difference tol for params after EM run 
tol: 1.0e-50 # min val of any array before thresholding for num stab
large_deg_thr: 20 # threshold for degree above which logs used
random_online_update_msg: True # update messages sequentially or in random order
non_informative_init: True # initialise alpha, pi as uniform (True), or according to init part passed (False)
use_fastmath: True # only require within 4 ULP rather than 1 ULP for vector computations if True - can significantly speed up, but not requires SVML
planted_p: 0.8 # strength of initial partition relative to noise (of strength 1 - p)